# Generated by Django 5.2.6 on 2025-10-25 14:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0003_dress_max_rental_days_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='อัตราค่าคอมมิชชั่นเริ่มต้นของแพลตฟอร์ม เช่น 0.10 = 10%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('commission_min_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ค่าคอมขั้นต่ำต่อออเดอร์ (บาท)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT บนค่าคอมฯ (ทศนิยม) เช่น 0.07 = 7%', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ShopCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('commission_min_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-added_at',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='dressimage',
            options={'ordering': ('-uploaded_at',)},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='pricetemplate',
            options={'ordering': ('store', 'name')},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='commission_min_fee',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='commission_vat_rate',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dress',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='dress',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ค่ามัดจำ'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ค่าจัดส่ง'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='จำนวนสินค้า'),
        ),
        migrations.AlterField(
            model_name='dresspriceoverride',
            name='day_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dresspriceoverride',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pricetemplate',
            name='max_days',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pricetemplateitem',
            name='day_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pricetemplateitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('CREATED', 'สร้างแล้ว'), ('PAID', 'ชำระเงินแล้ว'), ('RETURNED', 'คืนชุดแล้ว'), ('SETTLED', 'ปิดโอนให้ร้านแล้ว')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='shippingbracket',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='shippingbracket',
            name='max_qty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shippingbracket',
            name='min_qty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='clamp_to_max',
            field=models.BooleanField(default=True, help_text='ถ้าเกินช่วงบนให้ใช้ค่าสูงสุด'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='max_rental_days',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='pricetemplate',
            unique_together={('store', 'name')},
        ),
        migrations.AddIndex(
            model_name='dress',
            index=models.Index(fields=['shop', 'name'], name='dress_dress_shop_id_1673d6_idx'),
        ),
        migrations.AddField(
            model_name='shopcommission',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='dress.shop'),
        ),
    ]
