# Generated by Django 5.2.6 on 2025-10-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0004_platformsettings_shopcommission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dresspriceoverride',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pricetemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pricetemplateitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dresspriceoverride',
            constraint=models.UniqueConstraint(fields=('product', 'day_count'), name='uniq_dress_override_day'),
        ),
        migrations.AddConstraint(
            model_name='pricetemplate',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_price_template_store_name'),
        ),
        migrations.AddConstraint(
            model_name='pricetemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'day_count'), name='uniq_price_template_item_day'),
        ),
    ]
