# Generated by Django 5.2.6 on 2025-11-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0005_alter_dresspriceoverride_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='size',
            field=models.TextField(blank=True, null=True, verbose_name='ขนาด'),
        ),
    ]
