# Generated by Django 5.2.6 on 2025-11-15 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0007_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('paid', 'ชำระเงินแล้ว'), ('cancelled', 'ยกเลิก'), ('completed', 'เช่าเสร็จแล้ว')], default='pending', max_length=20)),
                ('omise_charge_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to='dress.dress')),
                ('rental_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dress.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
