# Generated by Django 5.2.6 on 2025-11-16 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0008_rentalorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('order', 'คำสั่งเช่า'), ('payment', 'การชำระเงิน'), ('reminder', 'เตือนเวลา'), ('shop_message', 'ข้อความจากร้าน'), ('system', 'ระบบ')], default='order', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='dress.rentalorder')),
                ('sender_shop', models.ForeignKey(blank=True, help_text='ถ้าเป็นข้อความจากร้าน ระบุร้านที่ส่ง', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='dress.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
