# Generated by Django 5.2.6 on 2025-11-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='shop_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
