# Generated by Django 5.2.6 on 2025-11-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0011_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dress.rentalorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dress.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
