# Generated by Django 5.2.8 on 2025-11-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0012_storetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='status',
            field=models.CharField(choices=[('new', 'คำเช่าใหม่'), ('waiting_payment', 'รอชำระเงิน'), ('paid', 'ชำระเงินสำเร็จ'), ('preparing', 'กำลังเตรียมจัดส่ง'), ('shipping', 'จัดส่งเรียบร้อย'), ('in_rental', 'อยู่ระหว่างการเช่า'), ('waiting_return', 'รอคืนชุด'), ('returned', 'คืนชุดแล้ว'), ('damaged', 'พบปัญหาชุดชำรุด'), ('cancelled', 'ออเดอร์ยกเลิก'), ('pending', 'รอดำเนินการ (เดิม)'), ('completed', 'เช่าเสร็จแล้ว (เดิม)')], default='new', max_length=30),
        ),
    ]
