# Generated by Django 5.2.8 on 2025-11-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0014_shopchatthread_shopchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopchatthread',
            name='related_dress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='dress.dress'),
        ),
    ]
