# Generated by Django 5.2.8 on 2025-11-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0015_shopchatthread_related_dress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopchatmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='ไฟล์ภาพที่แนบมากับข้อความแชท', null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='shopchatmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
