# Generated by Django 5.2.8 on 2025-12-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0017_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='dress.shopchatthread'),
        ),
    ]
