# Generated by Django 5.2.8 on 2025-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0018_notification_chat_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='เก็บลงคลัง / ซ่อนจากลูกค้า'),
        ),
    ]
