# Generated by Django 5.2.8 on 2025-12-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0021_shop_approved_at_shop_approved_by_shop_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='bankbook_image',
            field=models.ImageField(blank=True, null=True, upload_to='img_shop_docs/bankbooks/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='img_shop_docs/id_cards/'),
        ),
    ]
