# Generated by Django 5.2.8 on 2025-12-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0022_shop_bankbook_image_shop_id_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
