# Generated by Django 5.2.8 on 2025-12-23 19:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0023_review_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='inspection_days',
            field=models.PositiveIntegerField(default=2, help_text='ร้านตรวจสภาพภายใน (วัน)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='late_fee_cap',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='เพดานค่าปรับรวม (บาท)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='late_fee_grace_hours',
            field=models.PositiveIntegerField(default=0, help_text='ผ่อนผัน (ชั่วโมง) ก่อนเริ่มคิดค่าปรับ'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='late_fee_mode',
            field=models.CharField(choices=[('per_day', 'คิดต่อวัน'), ('per_hour', 'คิดต่อชั่วโมง'), ('percent_of_daily', 'คิดเป็น % ของราคาต่อวัน')], default='per_day', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='ค่าปรับคืนช้าต่อวัน (บาท)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='refund_days',
            field=models.PositiveIntegerField(default=5, help_text='คืนเงินภายใน (วันทำการ) หลังตรวจสภาพ'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='refund_method',
            field=models.CharField(choices=[('original_payment', 'คืนเข้าช่องทางเดิม'), ('manual_transfer', 'โอนคืนด้วยตนเอง')], default='original_payment', max_length=30),
        ),
    ]
