# Generated by Django 5.2.8 on 2025-12-23 20:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0024_platformsettings_inspection_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='late_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
