# Generated by Django 5.2.8 on 2025-12-27 06:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0025_rentalorder_late_days_rentalorder_late_fee_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('damaged', 'ชุดชำรุด'), ('not_returned', 'ไม่คืนชุด')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='damage_reports/')),
                ('status', models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_damage_reports', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='dress.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='dress.shop')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
