# Generated by Django 5.2.8 on 2025-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0026_damagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='img_shop_covers/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
