# Generated by Django 5.2.8 on 2025-12-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0027_shop_address_shop_cover_image_shop_line_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='allow_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='closed_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_sort',
            field=models.CharField(choices=[('newest', 'สินค้าใหม่ล่าสุด'), ('popular', 'ยอดนิยม'), ('price_low', 'ราคาต่ำไปสูง'), ('price_high', 'ราคาสูงไปต่ำ')], default='newest', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='products_per_page',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
