# Generated by Django 5.2.8 on 2025-12-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0028_shop_allow_reviews_shop_closed_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='is_open',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
