# Generated by Django 5.2.8 on 2025-12-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0029_alter_shop_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
