# Generated by Django 5.2.8 on 2025-12-29 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0030_shop_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DAMAGE', 'ชุดชำรุด/เสียหาย'), ('NOT_RETURNED', 'ไม่คืนชุด'), ('LATE_RETURN', 'คืนช้า'), ('CUSTOMER_SCAM', 'ลูกค้าโกง/หลอกลวง'), ('PAYMENT_DISPUTE', 'ปัญหาชำระเงิน')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('damage_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'ส่งแล้ว'), ('UNDER_REVIEW', 'กำลังตรวจสอบ'), ('NEED_MORE_INFO', 'ขอข้อมูลเพิ่ม'), ('RESOLVED', 'ปิดเคสแล้ว'), ('REJECTED', 'ปฏิเสธ')], default='SUBMITTED', max_length=30)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dress.rentalorder')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dress.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dress.report')),
            ],
        ),
    ]
