# Generated by Django 5.2.8 on 2026-01-02 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0031_report_reportattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('CUSTOMER', 'ลูกค้า/สมาชิก'), ('SHOP', 'หลังร้าน')], db_index=True, default='CUSTOMER', help_text='ระบุว่าแจ้งเตือนนี้เป็นของลูกค้าหรือหลังร้าน', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, help_text='คีย์กันแจ้งซ้ำ (ถ้าเป็น NULL จะไม่บังคับ unique)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_code',
            field=models.CharField(blank=True, choices=[('', 'ไม่ระบุ'), ('ORDER_NEW', 'ออเดอร์ใหม่เข้า'), ('NEED_SHIP', 'ต้องเตรียมจัดส่ง/ส่งมอบ'), ('RETURN_SOON', 'ใกล้วันรับคืน'), ('OVERDUE', 'เกินกำหนดคืน'), ('ORDER_ISSUE', 'ออเดอร์ยกเลิก/มีปัญหา'), ('CHAT_NEW', 'ข้อความใหม่จากลูกค้า'), ('REVIEW_NEW', 'รีวิวใหม่')], db_index=True, default='', help_text='ประเภทเหตุการณ์ของหลังร้าน (ใช้ทำกระดิ่ง/กรอง/สถิติ)', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, default='', help_text='ลิงก์สำหรับกดไปหน้าที่เกี่ยวข้อง (order detail/chat/review ฯลฯ)', max_length=300),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'dedupe_key'), name='uniq_notification_dedupe_per_user'),
        ),
    ]
