# Generated by Django 5.2.8 on 2026-02-02 05:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0032_notification_audience_notification_dedupe_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5, verbose_name='Rate คอมมิชชั่นที่ใช้ (ทศนิยม)'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ยอดหักค่าคอมมิชชั่น (เข้าแอดมิน)'),
        ),
        migrations.AddField(
            model_name='order',
            name='net_income_shop',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='รายได้สุทธิร้านค้า (โอนให้ร้าน)'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ยอดหัก VAT คอมมิชชั่น (เข้าแอดมิน)'),
        ),
    ]
