# Generated by Django 5.2.8 on 2026-02-05 06:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0033_order_applied_commission_rate_order_commission_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
